subscription_display_name = "Management"
billing_scope_id          = "/providers/Microsoft.Billing/billingAccounts/1234567/enrollmentAccounts/123456"
management_group_key      = "management"
owner_email               = "platform-team@contoso.com"
cost_center               = "CC-002"
location                  = "eastus"